#!/usr/bin/env bash
# Nexora self-host installer.
#
# Usage (one command, from a fresh Linux host):
#
#   curl -fsSL https://raw.githubusercontent.com/8w6s/nexora-install/main/install.sh | \
#     INVOICE=inv_2026_001 TOKEN=ghp_yourPAT bash
#
# What it does:
#   1. Verifies docker + docker compose are installed.
#   2. Logs in to GHCR with the customer PAT.
#   3. Generates ORDER_TOKEN_SECRET, DATABASE_ENCRYPTION_KEY,
#      NEXORA_LICENSE_SECRET (one-shot, written to ./nexora/.env).
#   4. Prompts (or reads from env) an admin password.
#   5. Writes ./nexora/docker-compose.yml pointing at the per-invoice image
#      ghcr.io/8w6s/nexora:latest-<INVOICE>.
#   6. `docker compose up -d`. Waits up to 90s for /api/health.
#   7. Prints admin URL + bootstrapped credentials. Done.
#
# Re-running the script:
#   It's idempotent — secrets in ./nexora/.env are preserved unless you
#   delete them. Re-run to upgrade after a new image tag is published.

set -euo pipefail

# ─── config ────────────────────────────────────────────────────────────
REGISTRY="${REGISTRY:-ghcr.io}"
IMAGE_REPO="${IMAGE_REPO:-ghcr.io/8w6s/nexora}"
INSTALL_DIR="${INSTALL_DIR:-$PWD/nexora}"
HOST_BACKEND_PORT="${HOST_BACKEND_PORT:-3000}"
HOST_FRONTEND_PORT="${HOST_FRONTEND_PORT:-4321}"
GHCR_USER="${GHCR_USER:-8w6s}"

# Required inputs — taken from env to keep the curl|bash invocation clean.
INVOICE="${INVOICE:-}"
TOKEN="${TOKEN:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@nexora.local}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"
PUBLIC_ORIGIN="${PUBLIC_ORIGIN:-http://localhost:${HOST_FRONTEND_PORT}}"

# Production mode REQUIRES https:// — anything else makes the backend bail
# on boot. Auto-pick NODE_ENV from the origin scheme so localhost installs
# don't accidentally trip that guard.
if [ -z "${NODE_ENV:-}" ]; then
  case "$PUBLIC_ORIGIN" in
    https://*) NODE_ENV=production ;;
    *)         NODE_ENV=development ;;
  esac
fi

# ─── helpers ───────────────────────────────────────────────────────────────
log()  { printf '\033[1;36m[nexora]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[nexora]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[nexora]\033[0m %s\n' "$*" >&2; exit 1; }
randhex() { openssl rand -hex 32; }

require_cmd() { command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"; }

# ─── preflight ─────────────────────────────────────────────────────────────
[ -n "$INVOICE" ] || die "INVOICE=<your invoice id> is required (e.g. INVOICE=inv_2026_001)"
# TOKEN is OPTIONAL: only needed if your Nexora GHCR namespace is private.
# The default release line publishes public images and the invoice-fetch
# token is baked into the image at build time (NEXORA_GHCR_TOKEN in the
# container env), so the host machine doesn't need any extra credentials.
: "${TOKEN:=}"

# Charset check — same shape the build workflow enforces.
echo "$INVOICE" | grep -Eq '^[A-Za-z0-9._-]{4,64}$' \
  || die "INVOICE has wrong shape (allowed: [A-Za-z0-9._-]{4,64})"

require_cmd docker
require_cmd openssl
docker compose version >/dev/null 2>&1 || die "docker compose plugin missing (apt install docker-compose-plugin or equivalent)"

# ─── ghcr login (only when TOKEN is supplied) ──────────────────────────
if [ -n "$TOKEN" ]; then
  log "logging in to $REGISTRY as $GHCR_USER"
  printf '%s' "$TOKEN" | docker login "$REGISTRY" --username "$GHCR_USER" --password-stdin >/dev/null \
    || die "GHCR login failed — is the PAT scoped read:packages on $REGISTRY?"
else
  log "no TOKEN supplied — assuming the Nexora package on $REGISTRY is public"
fi

# ─── filesystem layout ────────────────────────────────────────
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

ENV_FILE="$INSTALL_DIR/.env"
COMPOSE_FILE="$INSTALL_DIR/docker-compose.yml"

if [ ! -f "$ENV_FILE" ]; then
  log "first install — generating secrets into $ENV_FILE"
  if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-24)"
    GENERATED_ADMIN_PW=1
  fi
  {
    echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Kep this file private. Anyone who reads it can sign in as admin."
    echo "NEXORA_INVOICE_ID=$INVOICE"
    [ -n "$TOKEN" ] && echo "NEXORA_GHCR_TOKEN=$TOKEN"
    echo "NODE_ENV=$NODE_ENV"
    echo "PUBLIC_ORIGIN=$PUBLIC_ORIGIN"
    echo "ADMIN_EMAIL=$ADMIN_EMAIL"
    echo "ADMIN_PASSWORD=$ADMIN_PASSWORD"
    echo "ORDER_TOKEN_SECRET=$(randhex)"
    echo "DATABASE_ENCRYPTION_KEY=$(randhex)"
    echo "NEXORA_LICENSE_SECRET=$(randhex)"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
else
  log "$ENV_FILE already exists — preserving existing secrets"
  # Keep the existing secrets but make sure the invoice id + token are current.
  python3 - "$ENV_FILE" "$INVOICE" "$TOKEN" <<'PY'
import sys, re, io, os
path, inv, tok = sys.argv[1], sys.argv[2], sys.argv[3]
with io.open(path, "r", encoding="utf-8") as f: lines = f.readlines()
def upsert(lines, key, val):
    pat = re.compile(rf"^{re.escape(key)}=")
    for i, l in enumerate(lines):
        if pat.match(l):
            lines[i] = f"{key}={val}\n"; return
    lines.append(f"{key}={val}\n")
upsert(lines, "NEXORA_INVOICE_ID", inv)
if tok:
    upsert(lines, "NEXORA_GHCR_TOKEN", tok)
with io.open(path, "w", encoding="utf-8") as f: f.writelines(lines)
PY
  GENERATED_ADMIN_PW=0
fi

# ─── compose ───────────────────────────────────
cat > "$COMPOSE_FILE" <<YAML
services:
  nexora:
    image: ${IMAGE_REPO}:latest-${INVOICE}
    restart: unless-stopped
    env_file: .env
    ports:
      - "${HOST_BACKEND_PORT}:3000"
      - "${HOST_FRONTEND_PORT}:4321"
    volumes:
      - nexora-db:/app/data
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:3000/api/health >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  nexora-db:
YAML

log "pulling ${IMAGE_REPO}:latest-${INVOICE}"
docker compose -f "$COMPOSE_FILE" pull --quiet

log "starting nexora"
docker compose -f "$COMPOSE_FILE" up -d

# ─── wait for healthy ──────────────────────────────────────────────────────
log "waiting for backend on http://localhost:${HOST_BACKEND_PORT}/api/health"
for i in $(seq 1 30); do
  if curl -fsS --max-time 4 "http://localhost:${HOST_BACKEND_PORT}/api/health" >/dev/null 2>&1; then
    READY=1; break
  fi
  sleep 3
done

if [ -z "${READY:-}" ]; then
  warn "backend did not reach /api/health within ~90s. Recent logs:"
  docker compose -f "$COMPOSE_FILE" logs --tail=40 nexora >&2 || true
  die "install incomplete — fix the issue above and re-run the script (your .env is preserved)."
fi

# ─── done ────────────────────────────────────────────────────────────────
echo
log "Nexora is up."
echo "  Storefront:  http://localhost:${HOST_FRONTEND_PORT}/"
echo "  Admin:       http://localhost:${HOST_FRONTEND_PORT}/admin"
echo "  Email:       ${ADMIN_EMAIL}"
if [ "${GENERATED_ADMIN_PW:-0}" = "1" ]; then
  echo "  Password:    ${ADMIN_PASSWORD}    (generated; saved in ${ENV_FILE})"
else
  echo "  Password:    (unchanged — see ${ENV_FILE})"
fi
echo
echo "Useful commands:"
echo "  docker compose -f ${COMPOSE_FILE} logs -f"
echo "  docker compose -f ${COMPOSE_FILE} down       # stop"
echo "  docker compose -f ${COMPOSE_FILE} pull && docker compose -f ${COMPOSE_FILE} up -d   # upgrade"