import { Database } from "bun:sqlite";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/bun-sqlite";
import * as schema from "./schema.ts";

// Resolve DB path absolutely so cwd-dependent invocations (root vs backend/)
// always hit the same file. DB_PATH env wins; default = <repo>/backend/sqlite.db.
// Previously the file was implicitly "./sqlite.db" relative to cwd, which meant
// `bun run sed` from repo root and `bun run dev` from backend wrote to two
// different SQLite files.
const __here = dirname(fileURLToPath(import.meta.url));
const DB_PATH = Bun.env.DB_PATH ? resolve(Bun.env.DB_PATH) : resolve(__here, "../../sqlite.db");
export const sqlite = new Database(DB_PATH);

// WAL + sane defaults: WAL lets readers proceed during writes (watcher tick
// doesn't block API requests), busy_timeout retries instead of throwing
// SQLITE_BUSY, foreign_keys is OFF by default in SQLite (!) — we need it on
// for the FK cascades baked into the schema to actually fire.
sqlite.exec("PRAGMA journal_mode = WAL;");
sqlite.exec("PRAGMA synchronous = NORMAL;");
sqlite.exec("PRAGMA busy_timeout = 5000;");
sqlite.exec("PRAGMA foreign_keys = ON;");

/**
 * Minimal forward-only SQL migrator.
 */
function runMigrations(db: Database): void {
  // In the compiled production binary, `import.meta.url` points at a
  // virtual `compile://` path that has no on-disk equivalent. The
  // Dockerfile sets NEXORA_MIGRATIONS_DIR to the real /app/src/db/migrations
  // location; respect it when present so the migrator finds its SQL files.
  // In dev / tests the env var is unset and we fall back to the source-tree
  // resolution which is what `bun --watch src/index.ts` expects.
  const envDir = process.env.NEXORA_MIGRATIONS_DIR;
  const dir = envDir && envDir.trim().length > 0
    ? envDir
    : join(dirname(fileURLToPath(import.meta.url)), "migrations");
  if (!existsSync(dir)) return; // No migrations folder yet → silent no-op.

  let files: string[];
  try {
    files = readdirSync(dir)
      .filter((f) => f.endsWith(".sql"))
      .sort();
  } catch {
    return; // Unreadable folder → no-op rather than crash boot.
  }
  if (files.length === 0) return;

  // Tracking table: created on first migrator run, then queried each boot.
  db.exec(`CREATE TABLE IF NOT EXISTS _migrations (
    filename TEXT PRIMARY KEY,
    applied_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000)
  )`);

  const applied = new Set(
    db
      .query("SELECT filename FROM _migrations")
      .all()
      .map((r: any) => r.filename as string),
  );

  for (const file of files) {
    if (applied.has(file)) continue;
    const sql = readFileSync(join(dir, file), "utf8");
    // Each migration runs in its own transaction so a syntax error in
    // one file can't half-apply. The try/catch surfaces the offending
    // filename — bun:sqlite otherwise reports only a byteOffset which is
    // useless when nine migrations are queued behind a fresh shop boot.
    //
    // 0000_init.sql carries the full HEAD schema (generated by
    // drizle-kit at build time). On a brand-new DB it creates every
    // table. On an existing dev DB it would conflict — but we mark each
    // legacy file applied as soon as it errors with "duplicate column" or
    // "already exists", since the column/table is already there from a
    // prior boot. This lets fresh customer installs use 0000 alone while
    // legacy databases keep applying 0001+ deltas idempotently.
    try {
      db.transaction(() => {
        db.exec(sql);
        db.query("INSERT INTO _migrations (filename) VALUES (?)").run(file);
      })();
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      if (/duplicate column|already exists/i.test(msg)) {
        db.query("INSERT OR IGNORE INTO _migrations (filename) VALUES (?)").run(file);
        console.warn(`[migrate] ${file} skipped (schema already at this state)`);
        continue;
      }
      console.error(`[migrate] ${file} failed:`, msg);
      throw e;
    }
  }
}

runMigrations(sqlite);

// Downgrade guard: refuse to boot if DB was migrated by a newer build.
// Compares highest applied migration index against SCHEMA_VERSION baked in.
function assertNoDowngrade(database: Database): void {
  try {
    const mod = require("../lib/app-version.ts");
    const schemaVersion = mod.SCHEMA_VERSION as number;
    const rows = database.query("SELECT filename FROM _migrations").all() as Array<{
      filename: string;
    }>;
    let dbMax = 0;
    for (const r of rows) {
      const m = r.filename.match(/^(\d+)_/);
      if (m) {
        const n = Number(m[1]);
        if (n > dbMax) dbMax = n;
      }
    }
    if (dbMax > schemaVersion) {
      console.error(
        `[boot] FATAL: DB migrated to schema ${dbMax} but this build only knows up to ${schemaVersion}.`,
      );
      console.error(
        "[boot] Likely cause: downgraded Docker image after an update. Pull latest image or restore pre-update backup.",
      );
      process.exit(1);
    }
  } catch (e) {
    if (Bun.env.NEXORA_DEBUG_BOOT) console.warn("[boot] downgrade guard skipped:", e);
  }
}

assertNoDowngrade(sqlite);

export const db = drizzle(sqlite, { schema });
